### PR TITLE
Alternative to support multiple x509 Certificates via procs

### PR DESCRIPTION
**Pull request by pelted**
### What this PR does
- allows for looking up x509 certificates with a proc in the SamlIdp config
- calls the proc or falls back to the original behavior where appropriate
- adds short example in the REDME documentation

### Why

This is an alternative approach to supporting multiple x509 certificates, secret keys, and password. This uses procs in the SamlIdp configuration as an alternative to #186 and #209.

I have been using this approach for some time now using a service object as a finder for the appropriate cert and secret key.

Some examples for looking these up:

```ruby
config.x509_certificate = -> { File.read("cert.pem") }
config.secret_key = -> { SecretKeyFinder.key_for(id: 1) }
config.password = -> { Rails.application.credentials.dig(:saml_idp, :password ) }
```

### CODE REVIEW

**Comment by pelted** [comment]
Not sure if that's a flaky test in CI, still trying to reproduce the issue locally to resolve.

**Comment by Zogoo** [comment]
@pelted in here also, I think you have valid points, let us properly look at it and merge it after you fix the tests.

**Comment by Zogoo** [comment]
> Not sure if that's a flaky test in CI, still trying to reproduce the issue locally to resolve.

You are right it seems like failing everywhere, let me look at it.

**Review by atishedcast — APPROVED** [review]

**Comment by atishedcast** [comment]
any progress on this?
 I am looking for a similar solution.

**Comment by pelted** [comment]
@Zogoo I believe my latest commit should resolve the failing test if we could kick off the CI workflow and verify.

**Review by Zogoo — APPROVED** [review]
This is a valuable change in that the application can set the certificates on the fly.

**Comment by Zogoo** [comment]
@jphenow I think this is an alternative way to support thread-safe configuration. Could you please take a look at it?

**Comment by Zogoo** [comment]
@pelted can you update again with the latest master branch?

**Review by jphenow — APPROVED** [review]

**Pull request merged**
