### PR TITLE
[97] Rotation certificates

### PR DESCRIPTION
**Pull request by JuarezLustosa**
This is for issue #97 

This pr gives the gem support to the rotation certificate. In case you have many providers and the certificate expires, with this option you can change one by one without having to stop all your services.

### CODE REVIEW

**Comment by jphenow** [comment]
Love this addition. Do you have thoughts on making it an array of certificates? It seems like we could almost as easily accept an array of cert objects or hashes and get a slightly more flexible option.

**Comment by JuarezLustosa** [comment]
> Love this addition. Do you have thoughts on making it an array of certificates? It seems like we could almost as easily accept an array of cert objects or hashes and get a slightly more flexible option.

Yes. It can be awesome using an array. I'll take a look

**Comment by Zogoo** [comment]
@jphenow , @JuarezLustosa  It looks very nice to have this feature.
But, I have a different opinion about the rotation of certificate. Mostly this feature related to application side which uses saml_idp gem. We should make this gem as could possible as follow SAML protocol.

My proposal is If we could update config (SamlIdP.config) as possible to dynamically setup. You don't need to a new feature in the gem. Because you can change certificates before process SAML request in your application side. For example, If you have some active record model or even some hard coded config arrays which convertable to SamlIdP.config  then you can just load different configs from there. So let's update some logics to allow config object setup as dynamically.

**Comment by Zogoo** [comment]
As far I understand if we really want to support multiple certificates. Behavior should be different just switch keys with flag. 
https://stackoverflow.com/questions/35909251/saml2-metadata-multiple-signing-certificates

**Comment by Zogoo** [comment]
@jphenow, @JuarezLustosa  if you guys agree with my suggestion, I would like to suggest to close this pull request. And to create a new feature request that support SAML multiple certificate feature.

**Comment by JuarezLustosa** [comment]
> @jphenow, @JuarezLustosa if you guys agree with my suggestion, I would like to suggest to close this pull request. And to create a new feature request that support SAML multiple certificate feature.

@Zogoo It's ok to me, you can close this.

**Pull request closed without merging**
